pipeline:
  build:
    image: node:8-alpine
    commands:
      - npm install
      - npm run lint

  publish:
    image: plugins/docker
    repo: docker-registry.meringlab.org:5443/paxdb/api
    registry: docker-registry.meringlab.org:5443
    auto_tag: true
    secrets: [ docker_username, docker_password ]


# stable-master pattern
branches: master
