pipeline:
  build:
    image: node:8-alpine
    commands:
      - npm install
      - npm run lint
      - npm test

  publish:
    image: plugins/docker
    repo: docker-registry.meringlab.org:5443/paxdb/api
    registry: docker-registry.meringlab.org:5443
    auto_tag: true
    secrets: [ docker_username, docker_password ]

  slack_blame:
      image: plugins/slack-blame
      secrets: [ slack_token ]
      channel: paxdb-build-bot
      success_template: |
          paxdb/species-api build is green :) Thanks {{user.name}}
      failure_template: |
          paxdb/species-api build is broken :( Blame {{user.name}}
      when:
          status: [ failure, success ]



# stable-master pattern
branches: master
